[safety]
max_voltage = 5.0
max_current = 0.5
confirm_above_voltage = 3.3
confirm_above_current = 0.25
allowed_channels = [1, 2, 3]

[[resources]]
alias = "sim-e36103b"
resource = "USB0::SIM::E36103B::INSTR"
max_voltage = 3.3
max_current = 0.1
allowed_channels = [1]
