from __future__ import annotations

from pathlib import Path
import subprocess

from setuptools.command.build_py import build_py as _build_py
from setuptools import setup


ROOT = Path(__file__).resolve().parent.parent


def _git(*arguments: str) -> str:
    result = subprocess.run(
        ["git", *arguments],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return result.stdout.strip()


class build_py(_build_py):
    def run(self) -> None:
        super().run()
        try:
            source_commit = _git("rev-parse", "HEAD")
            source_dirty = bool(_git("status", "--porcelain"))
        except (OSError, subprocess.CalledProcessError):
            source_commit = "unknown"
            source_dirty = True
        target = Path(self.build_lib) / "powers_tool_validation" / "_build_metadata.py"
        target.write_text(
            "# Generated by the validation build.\n"
            f"SOURCE_COMMIT = {source_commit!r}\n"
            f"SOURCE_DIRTY = {source_dirty!r}\n"
            "ARTIFACT_KIND = 'wheel'\n",
            encoding="utf-8",
            newline="\n",
        )


setup(cmdclass={"build_py": build_py})
